# Lab 1 – Python, NumPy, and Pandas



**Importing code from `lab.py`**:

* Below, we import the `.py` file that's contained in the same directory as this notebook.
* We use the `autoreload` notebook extension to make changes to our `lab.py` file immediately available in our notebook. Without this extension, we would need to restart the notebook kernel to see any changes to `lab.py` in the notebook.
    - `autoreload` is necessary because, upon import, `lab.py` is compiled to bytecode (in the directory `__pycache__`). Subsequent imports of `lab` merely import the existing compiled python.

In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
from lab import *

In [4]:
from pathlib import Path
import io
import pandas as pd
import numpy as np

Let's get started! 🎉

## Part 1: Python Basics 🐍

### Question 0 – Consecutive Integers

Complete the implementation of the function `consecutive_ints`, which takes in a possibly empty list of integers (`ints`) and returns `True` if there exist two adjacent list elements that are consecutive integers and `False` otherwise.

For example, since `9` is next to `8`, `consecutive_ints([5, 3, 6, 4, 9, 8])` should evaluate to `True`, since `9` and `8` are consecutive integers. On the other hand, `consecutive_ints([1, 3, 5, 7, 9])` should evaluate to `False`.



In [4]:
# The cells below are here for you to write scratch work in. 
# You should write the code for your answer in `lab.py`, not here.

In [5]:
consecutive_ints([5, 3, 6, 4, 9, 8]) #This should evaluate to True

True

In [6]:
consecutive_ints([1, 3, 5, 7, 9]) #This should evaluate to False

False

In [11]:
consecutive_ints([])

False

### Question 1 – Median vs. Mean

Complete the implementation of the function `median_vs_mean`, which takes in a non-empty list of numbers (`nums`) and returns `True` if median of the list is less than or equal to the mean of the list and `False` otherwise.

Recall, if a list has even length, the median is the mean of the middle two elements.

***Note:*** In this question, you may only use built-in functions and methods in Python. You should not use `numpy` or `pandas` at all, nor should you import any additional packages.

In [4]:
median_vs_mean([1, 3, 4])

False

In [5]:
median_vs_mean([1, 3, 5, 8])

True

In [6]:
median_vs_mean([])

False

### Question 2 – Same Difference

Complete the implementation of the function `same_diff_ints`, which takes in a list of integers (`ints`) and returns `True` if there exist two list elements $i$ positions apart, whose absolute difference as integers is also $i$. If there are no two elements satisfying this condition, `same_diff_ints` should return `False`.

For example, because `3` (position 1) `5` (position 3) are 2 positions apart, and $|3-5| = 2$:
```py
>>> same_diff_ints([5, 3, 1, 5, 9, 8])
True
```
Whereas:
```py
>>> same_diff_ints([1, 3, 5, 7, 9])
False
```

***Important:*** While implementing `same_diff_ints`, we will assume that `ints` tends to satisfy the condition, and that the pair(s) saitifying the condition tend to be close together. As such, you must implement `same_diff_ints` such that it **runs quicker in cases where the pairs are close together than in cases where the pairs are further apart**. While you will still likely need a nested `for`-loop, this will inform how you configure your loop variables. (Optimizing your code for an assumed distribution of incoming data is very common in data science).

***Hints:*** 
- This is similar to Question 0.
- Make sure to define some extreme test cases, like when `ints` is an empty list. Also, use the `%%time` magic command to time your function, to make sure it satisfies the optimization requirement above.

In [6]:
%%time
same_diff_ints([])

CPU times: total: 0 ns
Wall time: 0 ns


False

In [21]:
%%time
same_diff_ints([3, 5, 1])

CPU times: total: 0 ns
Wall time: 0 ns


True

Make sure your function runs in under 5 seconds.

In [16]:
%%time
same_diff_ints([5, 3, 1, 5, 9, 8])

CPU times: total: 0 ns
Wall time: 0 ns


True

## Part 2: Strings and Files 🧵

The following questions will familiarize you with the basics of working with strings and reading data from files. Remember that by default, data from files are stored as strings in Python.

### Question 3 – $n$ Prefixes

Complete the implementation of the function `n_prefixes`, which takes a string `s` and a positive integer `n`. It returns a string containing the first `n` consecutive prefixes of `s` in reverse order.

For example, let's suppose `s` is the string `'Billy!'` and `n` is `4`. The consecutive prefixes of `'Billy!'` are:
- `'B'`
- `'Bi'`
- `'Bil'`
- `'Bill'`
- `'Billy'`
- `'Billy!'`

The first 4 of these are `'B'`, `'Bi'`, `'Bil'`, and `'Bill'`. If we combine these 4 in reverse order, we get `'BillBilBiB'`, which is what `n_prefixes('Billy!', 4)` should return. As another example, `n_prefixes('Marina', 3)` should return `'MarMaM'`. **You may assume that `n` is no larger than the length of `s`.**

***Hint:*** Recall that [strings may be sliced](https://docs.python.org/3/tutorial/introduction.html#strings), like lists.

In [24]:
n_prefixes('Billy!', 4)

'BillBilBiB'

In [25]:
n_prefixes('Marina', 3)

'MarMaM'

In [8]:
n_prefixes('', 2)

''

### Question 4 – Exploded Numbers 💣

Complete the implementation of the function `exploded_numbers`, which takes in a list of integers (`ints`) and a non-negative integer (`n`) and **returns a list of strings** containing numbers from the list expanded by `n` numbers in both directions, separated by spaces. Each integer should be [zero padded](https://www.tutorialspoint.com/python/string_zfill.htm) so that all integers outputted have the same length.

For example, consider `exploded_numbers([3, 8, 15], 2)`.
- If we explode 3 by 2 numbers in both directions, we get 1, 2, 3, 4, 5.
- If we explode 8 by 2 numbers in both directions, we get 6, 7, 8, 9, 10.
- If we explode 15 by 2 numbers in both directions, we get 13, 14, 15, 16, 17.

The longest length of any of the exploded numbers above is 2, so all of the outputted integers should have length 2.

- The string corresponding to 3 in the input is `'01 02 03 04 05'`.
- The string corresponding to 8 in the input is `'06 07 08 09 10'`.
- The string corresponding to 15 in the input is `'13 14 15 16 17'`.

So, `exploded_numbers([3, 8, 15], 2)` should return `['01 02 03 04 05', '06 07 08 09 10', '13 14 15 16 17']`. 

As another example, `exploded_numbers([9, 99], 3)` should return `['006 007 008 009 010 011 012', '096 097 098 099 100 101 102']`.

***Note***: You can assume that negative numbers will never be encountered. That is, when testing your code, we will never explode a number so much that it becomes negative.

In [11]:
exploded_numbers([3, 8, 15], 2)

['01 02 03 04 05', '06 07 08 09 10', '13 14 15 16 17']

In [12]:
exploded_numbers([9, 99], 3)

['006 007 008 009 010 011 012', '096 097 098 099 100 101 102']

## Part 3: `numpy` exercises 🥧



### Question 5 – Array Methods

Complete the implementations of the functions `add_root` and `where_square`. Specifications are given below. Your solutions should **not** contain any loops or list comprehensions.

#### `add_root`

`add_root` should take in a `numpy` array, `A`, and return a new `numpy` array that contains the element-wise sum of the elements in `A` with the _square roots of the positions of the elements in `A`_. 

For instance, if `A` contains the values 5, 9, and 4, the output array should contain the values 5 (5 + $\sqrt{0}$), 10 (9 + $\sqrt{1}$), and 5.4142... (4 + $\sqrt{2}$).

<br>

#### `where_square`

`where_square` should take in a `numpy` array, `A`, and return a new `numpy` array of Booleans whose `i`th element is `True` if and only if the `i`th element of `A` is a perfect square. 

For instance, `where_square(np.array([2, 9, 16, 15]))` should return `array([False, True, True, False])`.

In [6]:
add_root(np.array([5, 9, 4]))

array([ 5.        , 10.        ,  5.41421356])

In [7]:
where_square(np.array([2, 9, 16, 15]))

array([False,  True,  True, False])

In [9]:
A_1 = np.array([2, 4, 6, 7])
out_1 = add_root(A_1)
out_1

array([2.        , 5.        , 7.41421356, 8.73205081])

In [10]:
A_2 = np.array([1, 2, 16, 17, 32, 49])
out_2 = where_square(A_2)
out_2

array([ True, False,  True, False, False,  True])

In [8]:
# Don't change this cell 
A_1 = np.array([2, 4, 6, 7])
out_1 = add_root(A_1)

A_2 = np.array([1, 2, 16, 17, 32, 49])
out_2 = where_square(A_2)

### Question 6 – Stock Prices 📈

Complete the implementations of the functions `growth_rates` and `with_leftover`. Specifications are given below. Your solutions should **not** contain any loops or list comprehensions.

#### `growth_rates`

`growth_rates` should take in a `numpy` array, `A`, of [stock prices](https://en.wikipedia.org/wiki/Stock) for a single stock on successive days in USD. It should return an array of growth rates. That is, the `i`th number of the returned array should contain the rate of growth in stock price between the $i^{th}$ day to the $(i+1)^{th}$ day. The growth rate between two values is defined as $\frac{\text{final} - \text{initial}}{\text{initial}}$. You should return growth rates as **proportions, rounded to two decimal places**.

<br>

#### `with_leftover`

Again, suppose `A` is a `numpy` array of stock prices. Consider the following scheme: 

- Suppose that you start each day with \$20 to purchase stocks. 
- Each day, you purchase as many shares as possible of the stock. (The price changes each day, according to `A`.)
- Any money left-over after a given day is saved for possibly buying stock on a future day.

The function `with_leftover` should take in `A` and return the day (as an `int`) on which you can buy at least one full share using just "left-over" money. If this never happens, return `-1`. Note that the first stock purchase occurs on Day 0, and that you cannot purchase fractions of a share of a stock.

For example, if the stock price is \$3 every day, then the answer is `1` (corresponding to Day 1):
- Day 0: Buy 6 stocks with \\$20, and \\$2 is added to the leftover. Your total leftover is currently \\$2. This is not enough to buy one extra share, so you continue.
- Day 1: Buy 6 stocks with \\$20, and another \\$2 is added to the leftover. Your total leftover is now \\$4, so you can now buy one extra share. Hence, the answer is Day 1, and `with_leftover` should return `1`.

***Hint:*** `np.cumsum` may be helpful.

In [10]:
fp = Path('data') / 'stocks.csv'
stocks = np.array([float(x) for x in open(fp)])
out_3_stocks = growth_rates(stocks)
out_3_stocks

array([-0.  ,  0.01, -0.01,  0.  ,  0.  , -0.  ,  0.02,  0.01,  0.02,
        0.01,  0.01,  0.  ,  0.  ,  0.01, -0.  , -0.01, -0.  ,  0.  ,
       -0.01,  0.01,  0.  , -0.  ,  0.02,  0.  ,  0.01, -0.  ,  0.  ,
        0.01, -0.02,  0.01,  0.  , -0.01,  0.01,  0.  , -0.  , -0.01,
        0.01,  0.03, -0.01, -0.  ,  0.01,  0.01,  0.  ,  0.  , -0.  ,
        0.01,  0.01, -0.  ,  0.  ,  0.02, -0.01, -0.01,  0.01, -0.01,
        0.01,  0.02, -0.01, -0.01, -0.  ,  0.01,  0.  , -0.  ,  0.  ,
        0.01, -0.  ,  0.01, -0.  ,  0.01,  0.01,  0.01, -0.  , -0.  ,
        0.01,  0.  ,  0.  ,  0.02, -0.02, -0.  ,  0.01,  0.  ,  0.01,
        0.01, -0.  , -0.02, -0.01, -0.01, -0.01, -0.01,  0.  ,  0.01,
        0.01,  0.01, -0.  ,  0.  , -0.  , -0.01,  0.01,  0.01,  0.  ])

In [5]:
a = with_leftover(np.array([3, 3, 3, 3]))
a

1

In [46]:
# Don't change this cell -- it is needed for the tests to work
fp = Path('data') / 'stocks.csv'
stocks = np.array([float(x) for x in open(fp)])
out_3_stocks = growth_rates(stocks)

A_4 = np.array([3, 3, 3, 3])
out_4 = with_leftover(A_4)

## Part 4: Introduction to `pandas` 🐼

This part will help build familiarity with DataFrames in `pandas`. 

As always for `pandas` questions:
1. Avoid writing loops through the rows of the DataFrame to do the problem, and
2. Test the output/correctness of your code with the help of the dataset given, but be sure your code will also run on data that is similar to but different from the dataset given. (One way to do this is to sample rows from the provided DataFrame using the `.sample` method).

The file `data/salary.csv` contains salary information for the 2021-22 National Basketball Association (NBA) season 🏀. Specifically, it contains the name, team, and salary of all players who have played at least 15 games last season. We will load this file and store it as a DataFrame named `salary`.

In [43]:
# Do not edit this cell -- it is needed for the tests
salary_fp = Path('data') / 'salary.csv'
salary = pd.read_csv(salary_fp)
salary.head(n=381)

Player Position                Team    Salary
0         John Collins       PF       Atlanta Hawks  23000000
1     Danilo Gallinari       PF       Atlanta Hawks  20475000
2    Bogdan Bogdanović       SG       Atlanta Hawks  18000000
3         Clint Capela        C       Atlanta Hawks  17103448
4         Delon Wright       SG       Atlanta Hawks   8526316
..                 ...      ...                 ...       ...
376      Aaron Holiday       PG  Washington Wizards   3980551
377      Corey Kispert       SF  Washington Wizards   3383640
378          Raul Neto       PG  Washington Wizards   2089448
379     Daniel Gafford        C  Washington Wizards   1782621
380       Anthony Gill       PF  Washington Wizards   1517981

[381 rows x 4 columns]

### Question 7 – `pandas` Basics

Your job is to complete the implementation of the function `salary_stats`, which takes in a DataFrame like `salary` and returns a **Series** containing the following statistics:
- `'num_players'`: The number of players.
- `'num_teams'`: The number of teams.
- `'total_salary'`: The total salary amount for all players.
- `'highest_salary'`: The name of the player with the highest salary. **Assume there are no ties.**
- `'avg_los'`: The average salary of the `'Los Angeles Lakers'`, rounded to two decimal places.
- `'fifth_lowest'`: The name and team of the player who has the fifth lowest salary, separated by a comma and a space (e.g. `'Billy Triton, Cleveland Cavaliers'`). **Assume there are no ties.**
- `'duplicates'`: A Boolean that is `True` if there are any duplicate last names, and `False` otherwise. Note that some players may have a suffix on their name, such as "Jr." or "III" -- you should ignore these. That is, "Billy Triton Jr." and "Tyler Triton" should be considered to have the same last name.
- `'total_highest'`: The total salary of the team that has the highest paid player.

The index of each element in the outputted Series is specified above.

***Notes***: 
- Your function should work on a dataset of the same format that contains information from other years. This means that `salary_stats` should not "hard-code" any numbers or strings, but should compute them all programatically. In all cases, you may assume that none of the answers involving ranking involves a tie.
- The public tests don't test to see if your function actually returns the right numbers. You should manually inspect your result to make sure that all values seem appropriate.

In [18]:
salary_fp = Path('data') / 'salary_without_duplicates.csv'
salary = pd.read_csv(salary_fp)
stats = salary_stats(salary)
type(stats)
stats

num_players                                 5
num_teams                                   5
total_salary                        169524470
highest_salary                    Paul George
avg_los                            39344970.0
fifth_lowest      Kevin Durant, Brooklyn Nets
duplicates                              False
total_highest                        31610000
Name: Salary Stats, dtype: object

In [47]:
# check whether a player's name has more than 3 words
salary.loc[:, 'Player'].str.split(" ")
salary.loc[:, 'Player'].str.split(" ").str.len() > 3

0      False
1      False
2      False
3      False
4      False
       ...  
376    False
377    False
378    False
379    False
380    False
Name: Player, Length: 381, dtype: bool

In [ ]:
# Do not edit this cell 
salary_fp = Path('data') / 'salary.csv'
salary = pd.read_csv(salary_fp)
stats = salary_stats(salary)

salary_sample_fp = Path('data') / 'salary_sample.csv'
salary_sample = pd.read_csv(salary_sample_fp)
sample_stats = salary_stats(salary_sample)

## Congratulations! You're done Lab 1! 🏁

As a reminder, all of the work you want to submit needs to be in `lab.py`.
